import { escapeHtml } from '../utils/dom.js';

export function cleanBibReference(ref) {
  if (!ref || typeof ref !== 'string') return '';
  let s = ref.trim();
  const diacritics = [
    [/ˇc/g, 'č'], [/ˇC/g, 'Č'], [/´c/g, 'ć'], [/´C/g, 'Ć'],
    [/ˇs/g, 'š'], [/ˇS/g, 'Š'], [/ˇz/g, 'ž'], [/ˇZ/g, 'Ž'],
    [/¨o/g, 'ö'], [/¨O/g, 'Ö'], [/¨u/g, 'ü'], [/¨U/g, 'Ü'],
    [/¨a/g, 'ä'], [/¨A/g, 'Ä'], [/´e/g, 'é'], [/´E/g, 'É'],
    [/´a/g, 'á'], [/´A/g, 'Á'], [/´ı/g, 'í'], [/´i/g, 'í'],
    [/´o/g, 'ó'], [/´u/g, 'ú'], [/ˇr/g, 'ř'], [/ˇd/g, 'ď'],
    [/ˇt/g, 'ť'], [/ˇn/g, 'ň'], [/˚a/g, 'å'], [/˚A/g, 'Å']
  ];
  diacritics.forEach(([p, r]) => { s = s.replace(p, r); });
  s = s.replace(/Vrande\s+[čˇ]c?i[´c]/gi, 'Vrandečić')
       .replace(/Vrande\s+ˇci´c/gi, 'Vrandečić')
       .replace(/Kr\s*¨\s*otzsch/gi, 'Krötzsch')
       .replace(/Kr\s+ötzsch/gi, 'Krötzsch');
  s = s.replace(/\b([A-Z])\s+\.\s*/g, '$1. ');
  s = s.replace(/\b([A-Z]\.)\s+([A-Z])\s+\.\s*/g, '$1 $2. ');
  s = s.replace(/\s+([\,\.\:\;\?\!])/g, '$1');
  s = s.replace(/“\s+/g, '“').replace(/\s+”/g, '”');
  s = s.replace(/(\bpp?\.\s*\d+)\s*[\-\–]\s*(\d+)/g, '$1–$2');
  s = s.replace(/\s{2,}/g, ' ').trim();
  return s;
}

export function generateGoogleScholarHtml(data) {
  const lines = [
    '<!-- Google Scholar & Academic Discoverability Meta Tags (Generated by CorpusLD) -->'
  ];

  const title = data.name || data.headline || '';
  if (title) {
    lines.push(`<meta name="citation_title" content="${escapeHtml(title)}">`);
  }

  const authors = Array.isArray(data.author) ? data.author : (data.author ? [data.author] : []);
  authors.forEach(auth => {
    if (typeof auth === 'object' && auth !== null) {
      if (auth.name) {
        lines.push(`<meta name="citation_author" content="${escapeHtml(auth.name)}">`);
        const aff = auth.affiliation;
        if (Array.isArray(aff)) {
          aff.forEach(a => {
            const affName = typeof a === 'object' ? a.name : a;
            if (affName) lines.push(`<meta name="citation_author_institution" content="${escapeHtml(affName)}">`);
          });
        } else if (aff) {
          const affName = typeof aff === 'object' ? aff.name : aff;
          if (affName) lines.push(`<meta name="citation_author_institution" content="${escapeHtml(affName)}">`);
        }
      }
    } else if (typeof auth === 'string' && auth.trim()) {
      lines.push(`<meta name="citation_author" content="${escapeHtml(auth.trim())}">`);
    }
  });

  if (data.datePublished) {
    const dateSlash = String(data.datePublished).replace(/-/g, '/');
    lines.push(`<meta name="citation_publication_date" content="${escapeHtml(dateSlash)}">`);
    lines.push(`<meta name="citation_online_date" content="${escapeHtml(dateSlash)}">`);
  } else {
    lines.push('<!-- <meta name="citation_publication_date" content="YYYY/MM/DD"> (Date not identified in PDF, fill manually if needed) -->');
  }

  // Journal / Container
  const journalTitle = data.isPartOf?.name || (data.publisher?.note === 'inferred-journal' ? data.publisher?.name : '');
  if (journalTitle) {
    lines.push(`<meta name="citation_journal_title" content="${escapeHtml(journalTitle)}">`);
  }
  const vol = data.volumeNumber || data.isPartOf?.volumeNumber;
  if (vol) lines.push(`<meta name="citation_volume" content="${escapeHtml(vol)}">`);
  const issue = data.issueNumber || data.isPartOf?.issueNumber;
  if (issue) lines.push(`<meta name="citation_issue" content="${escapeHtml(issue)}">`);
  if (data.pageStart) lines.push(`<meta name="citation_firstpage" content="${escapeHtml(data.pageStart)}">`);
  if (data.pageEnd) lines.push(`<meta name="citation_lastpage" content="${escapeHtml(data.pageEnd)}">`);

  // DOI
  let doiVal = '';
  if (Array.isArray(data.identifier)) {
    const doiObj = data.identifier.find(i => String(i.propertyID || '').toUpperCase() === 'DOI');
    if (doiObj?.value) doiVal = String(doiObj.value).trim();
  }
  if (!doiVal && data.sameAs) {
    const mSame = String(data.sameAs).match(/doi\.org\/(10\.\S+)/i);
    if (mSame) doiVal = mSame[1];
  }
  if (doiVal) {
    lines.push(`<meta name="citation_doi" content="${escapeHtml(doiVal)}">`);
  }

  // ISSN
  let issnVal = data.issn || '';
  if (!issnVal && Array.isArray(data.identifier)) {
    const issnObj = data.identifier.find(i => String(i.propertyID || '').toUpperCase().includes('ISSN'));
    if (issnObj?.value) issnVal = String(issnObj.value).trim();
  }
  if (issnVal) {
    lines.push(`<meta name="citation_issn" content="${escapeHtml(issnVal)}">`);
  }

  // PDF URL & Abstract Landing Page URL
  if (data.encoding?.contentUrl) {
    lines.push(`<meta name="citation_pdf_url" content="${escapeHtml(data.encoding.contentUrl)}">`);
  }
  if (data.url) {
    lines.push(`<meta name="citation_abstract_html_url" content="${escapeHtml(data.url)}">`);
  }

  if (data.publisher?.name && data.publisher.note !== 'inferred-journal') {
    lines.push(`<meta name="citation_publisher" content="${escapeHtml(data.publisher.name)}">`);
  }

  if (data.inLanguage) {
    lines.push(`<meta name="citation_language" content="${escapeHtml(data.inLanguage)}">`);
  }

  if (data.keywords && data.keywords.length > 0) {
    const kwStr = Array.isArray(data.keywords) ? data.keywords.join('; ') : data.keywords;
    lines.push(`<meta name="citation_keywords" content="${escapeHtml(kwStr)}">`);
  }

  if (data.description) {
    lines.push(`<meta name="citation_abstract" content="${escapeHtml(data.description)}">`);
  }

  lines.push('<meta name="citation_fulltext_world_readable" content="">');

  const refs = data.citation || data.references_or_sources || [];
  if (Array.isArray(refs)) {
    refs.forEach(r => {
      if (typeof r === 'string' && r.trim().length > 10) {
        const cleanedR = cleanBibReference(r);
        if (cleanedR) {
          lines.push(`<meta name="citation_reference" content="${escapeHtml(cleanedR)}">`);
        }
      }
    });
  }

  return lines.join('\n');
}

export function generateHtmlHeadBundle(data) {
  const title = escapeHtml(data.name || data.headline || 'Academic Publication');
  const scholarMeta = generateGoogleScholarHtml(data);
  const allowedKeys = [
    '@context', '@type', '@id', 'name', 'headline',
    'description', 'inLanguage', 'datePublished', 'keywords', 'author',
    'hasPart', 'additionalProperty', 'citation', 'sdPublisher', 'action'
  ];
  const cleanObj = {};
  allowedKeys.forEach(k => {
    if (data[k] !== undefined && data[k] !== null && (Array.isArray(data[k]) ? data[k].length > 0 : true)) {
      cleanObj[k] = data[k];
    }
  });
  const jsonLdStr = JSON.stringify(cleanObj, null, 2);
  const indentedJson = jsonLdStr.split('\n').map(l => '    ' + l).join('\n');
  const indentedMeta = scholarMeta.split('\n').map(l => l ? '  ' + l : '').join('\n');

  return `<head>\n  <meta charset="UTF-8">\n  <meta name="viewport" content="width=device-width, initial-scale=1.0">\n  <title>${title}</title>\n\n${indentedMeta}\n\n  <!-- Schema.org Academic Knowledge Graph (JSON-LD) -->\n  <script type="application/ld+json">\n${indentedJson}\n  </script>\n</head>`;
}

export function renderScholarTab(data) {
  const scholarCode = document.getElementById('scholar-meta-code');
  if (scholarCode) {
    scholarCode.textContent = generateGoogleScholarHtml(data);
  }
  const headCode = document.getElementById('htmlhead-code');
  if (headCode) {
    headCode.textContent = generateHtmlHeadBundle(data);
  }
}

export function initScholarCopyHandlers() {
  document.getElementById('btn-copy-raw')?.addEventListener('click', () => {
    const code = document.getElementById('raw-jsonld-code')?.textContent || '';
    navigator.clipboard.writeText(code);
    alert('JSON-LD copied to clipboard!');
  });

  document.getElementById('btn-copy-htmlhead')?.addEventListener('click', () => {
    const code = document.getElementById('htmlhead-code')?.textContent || '';
    if (!code) return;
    navigator.clipboard.writeText(code);
    alert('Complete HTML <head> bundle copied to clipboard!');
  });

  const btnCopyScholar = document.getElementById('btn-copy-scholar');
  const btnCopyScholarTags = document.getElementById('btn-copy-scholar-tags');

  const copyScholarAction = () => {
    const code = document.getElementById('scholar-meta-code')?.textContent || '';
    if (!code) return;
    navigator.clipboard.writeText(code);
    alert('Google Scholar HTML Meta Tags copied to clipboard!');
  };

  if (btnCopyScholar) btnCopyScholar.addEventListener('click', copyScholarAction);
  if (btnCopyScholarTags) btnCopyScholarTags.addEventListener('click', copyScholarAction);
}
